type: update
name: Remove Application From Hasura
baseUrl: https://gitlab.hidora.com/softozor/hasura-jps/-/raw/master

settings:
  fields:
    - name: appId
      caption: Id
      type: string
      regex: ^[0-9a-fA-F]{8}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{12}$
      required: true
    - type: spacer
      caption: Fusionauth
    - name: almightyApiKey
      caption: Almighty API Key
      type: string
      inputType: password
      required: true

globals:
  ENV_VAR_NAME: HASURA_GRAPHQL_JWT_SECRET

onInstall:
  - updateUserMgmtActionsPermissions
  - removeAppIdFromHasuraJwtAudience
  - removeApplicationFromIamService
  - restartContainers[cp]  

actions:
  updateUserMgmtActionsPermissions:
    - cmd[auth]:
        - wget ${baseUrl}/fusionauth/get_application_roles_to_keep.py -O get_application_roles_to_keep.py
    - cmd[auth]: |-
        python3 ./get_application_roles_to_keep.py --api-url "http://localhost:9011" \
          --api-key "${settings.almightyApiKey}" \
          --app-id "${settings.appId}"
    - setGlobals:
        ROLES_TO_KEEP: ${response.out}
    - cmd[cp]:
        - wget ${baseUrl}/fusionauth/remove_user_mgmt_actions_permissions.py -O remove_user_mgmt_actions_permissions.py
    - cmd[cp]: |-
        python3 ./remove_user_mgmt_actions_permissions.py --actions-file /hasura-metadata/actions.yaml \
          --roles-to-keep "${globals.ROLES_TO_KEEP}"
  removeAppIdFromHasuraJwtAudience:
    - script: |
        const appId = "${settings.appId}"

        const resp = jelastic.environment.control.GetContainerEnvVarsByGroup({
          envName: '${env.appid}',
          session: session,
          nodeGroup: 'cp'
        })

        if (resp.result != 0) return resp

        const variablesDict = resp.object;
        if (!("${globals.ENV_VAR_NAME}" in variablesDict)) {
          return {
            result: 1,
            errOut: "variable ${globals.ENV_VAR_NAME} not found in the set of environment variables on 'cp' nodegroup: " + variablesDict
          }
        }

        const value = JSON.parse(variablesDict["${globals.ENV_VAR_NAME}"])

        value["audience"] = value["audience"].filter(function(value, index, arr){
            return value != appId
        })

        const vars = {
          "${globals.ENV_VAR_NAME}": value
        }

        jelastic.environment.control.AddContainerEnvVars({
          envName: '${env.appid}',
          session: session,
          nodeGroup: 'cp',
          vars: JSON.stringify(vars)
        })

        return {
          result: 0
        }
  removeApplicationFromIamService:
    - cmd[auth]:
        - wget ${baseUrl}/fusionauth/remove_application.py -O remove_application.py
    - cmd[auth]: |-
        python3 ./remove_application.py --api-url "http://localhost:9011" \
          --api-key "${settings.almightyApiKey}" \
          --app-id "${settings.appId}"